# This is a basic workflow to help you get started with Actions
name: CI
on:
  issues: 
    types: reopened
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: pwsh -File gitaction.ps1
      env:
        API_KEY: ${{ secrets.Azure_Token }}
        APP_Name: ${{ secrets.Azure_APPName }}
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "ghactions"
        git add .
        git commit -m "Update flavor of the day" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    - name: close issue
      uses: roots/issue-closer@v1.1
      with: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "this issue has been closed ready for next week"
        issue-pattern: "((?!This issue is used specifically to trigger a GitHub action.).)*"
